### ISSUE TITLE
Differential gene expression in command line

### ISSUE THREAD

**Issue by gurpreet-bioinfo** [onuryukselen/rnaseq#13]
Hi @onuryukselen,

DolphinNext paper says that differential gene expression is done via DEBrowser in GUI. Is there an option to do it via command line version of the pipeline or is it an upcoming feature?

Thanks.

**Comment by onuryukselen** [comment]
Hello, 
Because of the complexity of DE analysis, we're planning to keep this feature as it is and provide interactive analysis by using DEbrowser (https://debrowser.readthedocs.io/en/master/quickstart/quickstart.html) for short term.
Hopefully it helps.

**Comment by gurpreet-bioinfo** [comment]
Ok, thanks for the info.
